### ISSUE TITLE
Local run fails when using `uv` with a Python version built by `uv`

### ISSUE THREAD

**Issue by adriencaccia** [CodSpeedHQ/pytest-codspeed#76]
The following command fails with `.venv/bin/../lib/libpython3.12.so.1.0: cannot open shared object file: No such file or directory`:

```bash
codspeed run -- uv run pytest tests/
   PREPARING THE ENVIRONMENT 

Environment ready


   RUNNING THE BENCHMARKS 

/home/ubuntu/projects/codspeed/demo/.venv/bin/python: error while loading shared libraries: /home/ubuntu/projects/codspeed/demo/.venv/bin/../lib/libpython3.12.so.1.0: cannot open shared object file: No such file or directory
Error: failed to execute the benchmark process
```

## Steps to reproduce:

Create the following `pyproject.toml` file:

```toml
[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = [
    "pytest~=8.3.2",
    "pytest-benchmark~=4.0.0",
    "pytest-codspeed~=3.2.0",
]

[tool.uv]
required-version = ">=0.5.20" # will be picked up by the astral-sh/setup-uv GH action
```

Run the following command:

```bash
uv sync --all-extras --dev
codspeed run -- uv run pytest tests/ --codspeed
```
